name: Update datos.json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate datos.json
        run: |
          python DatosListaPartidos.py
      - name: Commit and push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add datos.json
          if git diff --cached --quiet; then
            echo 'No changes to commit'
          else
            git commit -m 'Update datos.json'
            git push
          fi
